FROM confluentinc/cp-kafka-connect:7.5.0

# Install Debezium PostgreSQL Connector
RUN confluent-hub install --no-prompt debezium/debezium-connector-postgresql:2.4.0 || \
    (curl -L https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/2.4.0.Final/debezium-connector-postgres-2.4.0.Final-plugin.tar.gz | \
    tar xz -C /usr/share/confluent-hub-components/)
